---Optimization and Graphics
NDefines.NGame.DAYS_BEHIND_PAUSE = 100
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 60
NDefines.NEngine.EVENT_PROCESS_OFFSET = 35
NDefines.NGraphics.CAPITAL_INDICATOR_HEIGHT_SCALE = 100.0
NDefines.NGraphics.CAPITAL_INDICATOR_HEIGHT = 0
NDefines.NGraphics.BORDER_WIDTH = 1
NDefines.NGraphics.DIRECTION_POINTER_DRAW_DISTANCE = 1000
NDefines.NGraphics.DIRECTION_POINTER_INTERPOLATION_SPEED = 0.1

--- AI
NDefines.NAI.DEVELOPMENT_CAP_BASE = 30

--- Diplo
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.CONDOTTIERI_MIN_DURATION = 1
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 10
NDefines.NDiplomacy.HRE_AUTHORITY_JOIN_EMPIRE = 0
NDefines.NDiplomacy.PS_MOVE_TRADE_PORT = 50
NDefines.NDiplomacy.PS_REPLACE_RIVAL = 0

--Economy
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 10
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NEconomy.CARAVAN_POWER_MAX = 30

---Country
NDefines.NCountry.MONARCH_MIN_SKILL = 1
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 10
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -50
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -30
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -30
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 30.5
NDefines.NCountry.MAXIMUM_CONDOTTIERI = 1
NDefines.NCountry.MINIMUM_POLICY_TIME = 5
NDefines.NCountry.NAT_FOCUS_YEARS = 15
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.PS_ASSAULT = 0
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 25
NDefines.NCountry.PS_GARRISON_SORTIES = 0
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0

--NMilitary
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 4

package.loaded["debug"] = nil
_G["debug"] = nil
debug = nil